steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'build'
        - '-t'
        - 'gcr.io/$PROJECT_ID/apfn-frontend'
        - '.'
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'push'
        - 'gcr.io/$PROJECT_ID/apfn-frontend'
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        - 'run'
        - 'deploy'
        - 'apfn-frontend-master'
        - '--image'
        - 'gcr.io/$PROJECT_ID/apfn-frontend:latest'
        - '--region'
        - 'europe-west1'
        - '--platform'
        - 'managed'
        - '--allow-unauthenticated'
